# Generated by Django 4.2.7 on 2026-03-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='info', max_length=20)),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('scan_duration', models.FloatField(default=0.0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('vulnerabilities_json', models.TextField(default='[]')),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
    ]
